//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BDokenDetail
    {
        [DisplayName("Token address")]
        public string BDID { get; set; }
        [DisplayName("Token Name")]
        public string BDname { get; set; }
        [DisplayName("Token symbol")]
        public string BDsymbol { get; set; }
        [DisplayName("Number of decimals")]
        public int BDdecimals { get; set; }
    }
}
