//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDokenDetail
    {
        public string BDID { get; set; }
        public string BDname { get; set; }
        public string BDsymbol { get; set; }
        public int BDdecimals { get; set; }
    }
}
