//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentID { get; set; }
        public Nullable<System.DateTime> paymentDatetime { get; set; }
        public decimal paymentSum { get; set; }
        public string videoTitle { get; set; }
        public string payerUsername { get; set; }
        public string receiverUsername { get; set; }
    }
}
